### ISSUE TITLE
As a user, be able to search for equipment in a specific area

### ISSUE THREAD

**Issue by Soblique** [sharemyski/sharemyski#6] opened 2020-03-20 00:53 UTC

**Comment by robotmatt** [comment] 2020-03-21 00:04
@Soblique @WilliamStephan do you think this is a duplicate of #7?

**Comment by Soblique** [comment] 2020-03-21 01:06
Yep, we only need 7.

**Comment by robotmatt** [comment] 2020-03-21 01:15
okay. closing this one out

**Closed by robotmatt** 2020-03-21 01:15 UTC
